### ISSUE TITLE
Benchmarks fail

### ISSUE THREAD

**Issue by tilenflare** [dwallet-labs/2pc-mpc#31]
Hi,
I was trying to test your implementation but it seems that your benchmarks give errors (threshold not reached). I think the problem is in file `src/sign.rs` part
```
#[cfg(feature = "benchmarking")]
pub(crate) mod benches {
    use criterion::Criterion;

    pub(crate) fn benchmark(_c: &mut Criterion) {
        // TODO: for loops
        super::tests::dkg_presign_signs_internal(8, 2, 1);
        super::tests::dkg_presign_signs_internal(16, 8, 1);
        super::tests::dkg_presign_signs_internal(32, 16, 1);
        super::tests::dkg_presign_signs_internal(32, 64, 1);
        super::tests::dkg_presign_signs_internal(64, 128, 1);
        super::tests::dkg_presign_signs_internal(256, 128, 1);
    }
}
```
If I understand correctly, the first input of the `dkg_presign_signs_internal` is threshold, the second is the number of parties, so 8,2 makes no sense to me.

**Comment by ycscaly** [comment]
This code is deprecated (although this should work), a new version will be released, I suggest to wait with the benchmarking
